name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.13
  flutter_test:
    sdk: flutter
  decorator:
    path: ../


flutter:
  uses-material-design: true