targets:
  $default:
    builders:
      decorator:
        enabled: true
        generate_for:
          - lib/*

builders:
  decorator:
    import: "package:decorator/builder.dart"
    builder_factories: ["decorator"]
    build_extensions: {".dart": [".d.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]