targets:
  $default:
    builders:
      decorator_generator|decorator:
        generate_for:
          - lib/*
        enabled: true

builders:
  decorator:
    import: "package:decorator/builder.dart"
    builder_factories: ["decoratorBuilder"]
    build_extensions: {".dart": [".decorator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]