name: decorator
description: A new Flutter package.
version: 0.0.1
author: Eugene Ostashko <ostashko4@gmail.com>
homepage: https://github.com/ReliableCauliflower/decorator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.10+1
  decorator_annotation:
    git: https://github.com/ReliableCauliflower/decorator_annotation

dev_dependencies:
  build_test: ^1.3.4
  build_runner: ^1.10.13
  test: ^1.15.7